#pragma once
#ifndef AXML_LABEL_ENCODER_HPP
#define AXML_LABEL_ENCODER_HPP

#include <vector>
#include <span>
#include <cmath>
#include <algorithm>
#include <ranges>
#include <concepts>
#include <stdexcept>
#include "common.hpp"

namespace AxML {

template <std::floating_point T>
class LabelEncoder {

public:
    /**
     * Encodes a contiguous array of floats into integer labels (0 to unique_count - 1).
     *
     * @param input A contiguous view of floats.
     * @return A vector of encoded integer indices.
     */
    std::vector<i32> encode_i32(std::span<const T> input) {
        if (input.empty()) {
            return {};
        }

        std::vector<T> rounded_input;
        rounded_input.reserve(input.size());

        for (const T val : input) {
            if (std::isnan(val)) {
                throw std::invalid_argument("NaN values cannot be sorted or encoded reliably.");
            }
            rounded_input.push_back(std::round(val));
        }

        unique_labels_ = rounded_input;

        std::ranges::sort(unique_labels_);
        auto [first, last] = std::ranges::unique(unique_labels_);
        unique_labels_.erase(first, last);

        std::vector<i32> encoded;
        encoded.reserve(input.size());

        // Cache the last lookup to accelerate repetitive sequential data
        T last_val = unique_labels_.front();
        int last_label = 0;
        bool cache_valid = false;

        for (const T val : rounded_input) {
            if (cache_valid && val == last_val) {
                encoded.push_back(last_label);
            } else {
                auto it = std::ranges::lower_bound(unique_labels_, val);
                last_label = static_cast<int>(std::distance(unique_labels_.begin(), it));
                last_val = val;
                cache_valid = true;

                encoded.push_back(last_label);
            }
        }

        return encoded;
    }

    std::vector<T> encode_scalar(std::span<const T> input) {
        if (input.empty()) {
            return {};
        }

        std::vector<T> rounded_input;
        rounded_input.reserve(input.size());

        for (const T val : input) {
            if (std::isnan(val)) {
                throw std::invalid_argument("NaN values cannot be sorted or encoded reliably.");
            }
            rounded_input.push_back(std::round(val));
        }

        unique_labels_ = rounded_input;

        std::ranges::sort(unique_labels_);
        auto [first, last] = std::ranges::unique(unique_labels_);
        unique_labels_.erase(first, last);

        std::vector<T> encoded;
        encoded.reserve(input.size());

        // Cache the last lookup to accelerate repetitive sequential data
        T last_val = unique_labels_.front();
        i32 last_label = 0;
        bool cache_valid = false;

        for (const T val : rounded_input) {
            if (cache_valid && val == last_val) {
                encoded.push_back(static_cast<T>(last_label));
            } else {
                auto it = std::ranges::lower_bound(unique_labels_, val);
                last_label = static_cast<i32>(std::distance(unique_labels_.begin(), it));
                last_val = val;
                cache_valid = true;

                encoded.push_back(static_cast<T>(last_label));
            }
        }

        return encoded;
    }

    /**
     * Decodes an integer label back to the original rounded floating-point value.
     *
     * @param label_index The integer label generated by encode().
     * @return The rounded floating-point value.
     */
    T decode(int label_index) const {
        if (static_cast<size_t>(label_index) >= unique_labels_.size()) {
            throw std::out_of_range("Label index out of bounds.");
        }
        return unique_labels_[label_index];
    }

    size_t unique_count() const noexcept {
        return unique_labels_.size();
    }

private:
    std::vector<T> unique_labels_;
};

}

#endif //AXML_LABEL_ENCODER_HPP